export const HOUSE_PLAN_FIELDS = [
  "id",
  "title",
  "price",
  "description",
  "img",
  "house_area",
  "boiler_room_area",
  "rooms",
  "bathrooms_and_wc",
  "plot_dimensions",
  "min_plot_dimensions_after_adaptation",
  "floors",
  "building_width",
  "building_length",
  "building_footprint",
  "total_area",
  "roof_type",
  "roof_angle",
  "garage",
  "architectural_style",
  "energy_standard",
  "basement",
  "building_height",
  "fireplace",
  "terrace",
  "house_type",
] as const
